apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          env:
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
          image: pluralsight_backend:latest
          imagePullPolicy: Never # only for local testing
          readinessProbe:
            httpGet:
              path: /api/v1/
              port: api
          livenessProbe:
            httpGet:
              path: /api/v1/
              port: api
          ports:
            - name: api
              containerPort: 8000
