apiVersion: batch/v1
kind: Job
metadata:
  name: ckad1
spec:
  activeDeadlineSeconds: 10
  ttlSecondsAfterFinished: 120
  completions: 5
  parallelism: 1
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ctr
        image: alpine:latest
        command: ['sh', '-c', 'echo "Lets smash the CKAD" && sleep 60']
