apiVersion: batch/v1
kind: Job
metadata:
  name: ckad1
spec:
  completions: 5
  parallelism: 1
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ctr
        image: alpine:latest
        command: ["echo",  "Let's smash the CKAD"]


