apiVersion: v1
kind: Pod
metadata:
  name: store-backend
  namespace: default
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: pluralsight_backend:latest
      ports:
        - containerPort: 8000
