apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lke-wait
provisioner: linodebs.csi.linode.com
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer