apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immediate
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: linode-block-storage